AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Module 3 (orders)

Globals:
  Api:
    TracingEnabled: true #Enables AWS X-Ray tracing for the API Gateway
  #Adding Idempotency to orders module
  Function:
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: orders
        POWERTOOLS_METRICS_NAMESPACE: ServerlessWorkshop
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:68

Parameters:
  UserPool:
    Type: String
    Description: User Pool ID produced by the Users module

Resources:
  # Amazon DynamoDB
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "orderId"
          AttributeType: "S"
      # Specifies the primary key. For Orders, the key is a composite of "userId" and "orderId".
      KeySchema:
        - AttributeName: "userId" # PARTITION KEY
          KeyType: "HASH"
        - AttributeName: "orderId" # SORT KEY
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
  
  # AWS API Gateway
  WorkshopApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: Module3CognitoAuthorizer
        Authorizers:
          Module3CognitoAuthorizer:
            UserPoolArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool}"
  
  #AWS Lambda
  AddOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/order/create
      Handler: create_order.lambda_handler
      Runtime: python3.14
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
        # Adding idempotency
        - DynamoDBCrudPolicy:
            TableName: !Ref IdempotencyTable
      Environment:
        Variables:
          TABLE_NAME: !Ref OrdersTable
          # Adding idempotency
          IDEMPOTENCY_TABLE_NAME: !Ref IdempotencyTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: post
            RestApiId: !Ref WorkshopApiGateway

  # Lambda Layer for Orders retrieval 
  PyUtils:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pyutils
      Description: Shared utilities for Orders service
      ContentUri: src/layers
      CompatibleRuntimes:
        - python3.14
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.14

  # AWS Lambda
  GetOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/order/get
      Handler: get_order.lambda_handler
      Runtime: python3.14
      Tracing: Active
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref OrdersTable
      Environment:
        Variables:
          TABLE_NAME: !Ref OrdersTable
      # Note the reference to PyUtils in the Layers attribute. That's all you need to make the Lambda layer available to your function!
      Layers:
        - !Ref PyUtils
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders/{orderId}
            Method: get
            RestApiId: !Ref WorkshopApiGateway
  
  # AWS Lambda
  ListOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/order/list
      Handler: list_orders.lambda_handler
      Runtime: python3.14
      Tracing: Active
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref OrdersTable
      Environment:
        Variables:
          TABLE_NAME: !Ref OrdersTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: get
            RestApiId: !Ref WorkshopApiGateway

  # AWS Lambda
  EditOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/order/edit
      Handler: edit_order.lambda_handler
      Runtime: python3.14
      Tracing: Active
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref OrdersTable
      Environment:
        Variables:
          TABLE_NAME: !Ref OrdersTable
      Layers:
        - !Ref PyUtils
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders/{orderId}
            Method: put
            RestApiId: !Ref WorkshopApiGateway
  
  # AWS Lambda
  CancelOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/order/cancel
      Handler: cancel_order.lambda_handler
      Runtime: python3.14
      Tracing: Active
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref OrdersTable
      Environment:
        Variables:
          TABLE_NAME: !Ref OrdersTable
      Layers:
        - !Ref PyUtils
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /orders/{orderId}
            Method: delete
            RestApiId: !Ref WorkshopApiGateway

  # Amazon DynamoDB
  IdempotencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiration
        Enabled: true
      BillingMode: PAY_PER_REQUEST

Outputs:
  OrdersServiceEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${WorkshopApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  
  OrdersTable:
    Description: "DynamoDB Orders Table"
    Value: !Ref OrdersTable